# Generated by Django 3.1.1 on 2020-09-27 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resturent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('location_id', models.CharField(default='', max_length=100)),
                ('address', models.TextField(default='')),
                ('categories', models.TextField(default='')),
                ('primaryCategories', models.TextField(default='')),
                ('city', models.CharField(default='', max_length=100)),
                ('country', models.CharField(default='', max_length=100)),
                ('keys', models.TextField(default='')),
                ('latitude', models.CharField(default='', max_length=100)),
                ('longitude', models.CharField(default='', max_length=100)),
                ('name', models.CharField(default='', max_length=100)),
                ('postalCode', models.CharField(default='', max_length=100)),
                ('province', models.CharField(default='', max_length=100)),
                ('sourceURLs', models.TextField(default='')),
                ('websites', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='UserLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fisrt_name', models.CharField(default='', max_length=100)),
                ('address', models.CharField(default='', max_length=100)),
                ('city', models.CharField(default='', max_length=50)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
