# Generated by Django 3.0.10 on 2020-10-25 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temple_audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdonation',
            name='donation_deposit_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
