# Generated by Django 3.0.10 on 2020-10-25 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temple_audit', '0002_auto_20201025_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdonation',
            name='donation_deposit_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='userdonation',
            name='mobile_number',
            field=models.CharField(default='', max_length=100),
        ),
    ]
