# Generated by Django 3.0.10 on 2020-10-25 07:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temple_audit', '0003_auto_20201025_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdonation',
            name='donation_amount',
            field=models.IntegerField(default=None, validators=[django.core.validators.RegexValidator(message="Donation amount should be 1 or > 1 Rs'.", regex='^[1-9][0-9]*$')]),
        ),
        migrations.AlterField(
            model_name='userdonation',
            name='donation_status',
            field=models.BooleanField(default=False, help_text='Donation amount deposited or not'),
        ),
        migrations.AlterField(
            model_name='userdonation',
            name='mobile_number',
            field=models.CharField(blank=True, default='', max_length=100, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+919993158005'. Up to 12 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
